Feature-create-update-module-workflow
basepair/basepair-python pull request #76
Opened 2021-12-14 11:24 UTC by siddhant-basepair

This PR will impart the following features to the CLI -

Create Module via YAML
Update Module via YAML
Create Workflow via YAML
Update Workflow via YAML
create module --yaml test.yaml
update module --yaml test.yaml
create workflow --yaml test.yaml
update workflow --yaml test.yaml

Ticket - https://app.asana.com/0/1201368373933132/1201406835914440

2021-12-23 11:56 UTC, Lalee10 requested changes
Rename `workflow` -> `pipeline` wherever possible

2021-12-23 14:06 UTC, siddhant-basepair commented
> Rename `workflow` -> `pipeline` wherever possible

@Lalee10 that is included in the future feedback PR

2021-12-23 14:15 UTC, Lalee10 approved these changes

2021-12-23 15:12 UTC, govind-basepair commented
<img width="1061" alt="Screenshot 2021-12-23 at 8 39 15 PM" src="https://user-images.githubusercontent.com/56910277/147259063-6a12a7b5-f3a8-4135-b6dd-bea391b178db.png">
Fix the pylint issues in all the files you have modified/added

2021-12-23 15:23 UTC, govind-basepair requested changes

2021-12-23 15:23 UTC, govind-basepair commented on basepair/api.py
> +  def create_module(self,data):
add method comment

2021-12-23 15:23 UTC, govind-basepair commented on basepair/api.py
> +  def create_module(self,data):
missing space after self,

2021-12-23 15:23 UTC, govind-basepair commented on basepair/api.py
> +          os.path.expandvars(data['yamlpath'])
make it a single line
`path = os.path.abspath(os.path.expanduser(os.path.expandvars(data['yamlpath'])))`

2021-12-23 15:23 UTC, govind-basepair commented on basepair/api.py
> +    payload = {"data":yaml_string}
use single quote here

2021-12-23 15:23 UTC, govind-basepair commented on basepair/api.py
> +    if yaml_data.get('id') == None:
you already have module_id variable defined in line 447. use that

2021-12-23 15:23 UTC, govind-basepair commented on basepair/api.py
> +  def create_workflow(self,data):
method comment missing

2021-12-23 15:23 UTC, govind-basepair commented on basepair/api.py
> +        eprint('created: workflow '+workflow_name+' with id', workflow_id)
use f string for string interpolation

2021-12-23 15:27 UTC, govind-basepair commented on basepair/helpers/nice_print.py
> +        module['created']
looks like it should be **date_created**

2021-12-23 15:29 UTC, govind-basepair commented on basepair/api.py
> +    return workflow_id
why is workflow_id returned in case of error? it should the API error response

2021-12-23 15:30 UTC, govind-basepair commented on basepair/infra/webapp/module.py
> +      result = parsed.get('objects')
no need of extra variable
`return parsed.get('objects')`

2021-12-23 15:38 UTC, govind-basepair requested changes

2021-12-23 15:38 UTC, govind-basepair commented on bin/basepair
> +    'yamlpath': args.yaml[0]
```
    yaml_path = args.yaml[0]
    if yaml_path.endswith('.yaml'):
      bp.create_workflow({'yaml_path': yaml_path})
    else:
      eprint('Please provide yaml file only')
```

2021-12-23 15:38 UTC, govind-basepair commented on bin/basepair
> +
remove empty line

2021-12-24 09:31 UTC, siddhant-basepair commented on basepair/helpers/nice_print.py
> +        module['created']
label is date_created from API i am sending it as 'created' key

2022-01-03 17:34 UTC, govind-basepair commented on basepair/api.py
> +      eprint('failed module update')
print API response error message

2022-01-03 17:41 UTC, siddhant-basepair commented on basepair/api.py
> +      eprint('failed module update')
it's already printing when API call is being made

2022-01-03 18:48 UTC, govind-basepair approved these changes

2022-01-03 18:48 UTC, merged