Improvement:added -f --file argument for .yaml .yml
basepair/basepair-python pull request #79
Opened 2021-12-27 15:03 UTC by siddhant-basepair

User should be able to create and update Module or Pipeline via -f or —file1
Example -
create module —file1 test.yaml or test.yml
create moudle -f test.yaml or test.yml

Related Ticket -
https://app.asana.com/0/1201368373933132/1201589980257997

2021-12-28 15:51 UTC, Lalee10 requested changes

2021-12-28 15:51 UTC, Lalee10 commented on bin/basepair
> +    '--file1',
What issue is faced when using `--file`?

2021-12-28 16:13 UTC, siddhant-basepair commented on bin/basepair
> +    '--file1',
changed it to file as well

2021-12-29 08:46 UTC, Lalee10 requested changes

2021-12-29 08:46 UTC, Lalee10 commented on basepair/api.py
> +      eprint('failed creating module')
log some information on why module creation failed, can we reuse `info.get('error')` here?

2021-12-29 08:46 UTC, Lalee10 commented on basepair/api.py
> +      eprint('failed updating module')
log some information on why module **update** failed, can we reuse `info.get('error')` here?

2021-12-29 08:46 UTC, Lalee10 commented on basepair/api.py
> +      eprint('failed creating pipeline')
log some information on why pipeline creation failed, can we reuse `info.get('error')` here?

2021-12-29 08:46 UTC, Lalee10 commented on basepair/api.py
> +      eprint('failed updating pipeline')
log some information on why pipeline update failed, can we reuse `info.get('error')` here?

2021-12-29 08:46 UTC, Lalee10 commented on basepair/api.py
> +      'ye': True,
remove `ye` as an acceptable answer, rest are fine

2021-12-29 08:46 UTC, Lalee10 commented on basepair/api.py
> +        get_input = raw_input
We don't support python 2, so you can just add code for python 3

![image](https://user-images.githubusercontent.com/38792700/147643674-52d52e14-2045-4354-8e78-f5f243912f3a.png)

2021-12-29 09:47 UTC, siddhant-basepair commented on basepair/api.py
> +      eprint('failed creating module')
error is already logging once without it so updated the over all status failure

2021-12-29 09:47 UTC, siddhant-basepair commented on basepair/api.py
> +      eprint('failed updating module')
API error's is already logging once without it so updated the overall status failure

2021-12-29 09:48 UTC, siddhant-basepair commented on basepair/api.py
> +      eprint('failed creating pipeline')
API error's is already logging once without it so updated the overall status failure

2021-12-29 09:48 UTC, siddhant-basepair commented on basepair/api.py
> +      eprint('failed updating pipeline')
API error's is already logging once without it so updated the overall status failure

2021-12-29 09:49 UTC, siddhant-basepair commented on basepair/api.py
> +      'ye': True,
done

2021-12-29 09:51 UTC, siddhant-basepair commented on basepair/api.py
> +        get_input = raw_input
Done

2021-12-29 10:54 UTC, Lalee10 requested changes
In each create and update method (both pipeline and module) we are repeating a number of step i.e.

1. Check if file provided
2. Check if only single file provided
3. Check if file YAML file

Please move this code to a common function

2021-12-29 10:54 UTC, Lalee10 commented on basepair/api.py
> +      get_input = input
remove unnecessary variable declaration and use directly

2021-12-29 10:54 UTC, Lalee10 commented on basepair/api.py
> +      eprint('failed creating module')
standardize the message `failed module creation`

2021-12-29 10:54 UTC, Lalee10 commented on basepair/api.py
> +      eprint('failed updating module')
change message -> `failed module update`

2021-12-29 10:54 UTC, Lalee10 commented on basepair/api.py
> +      eprint('failed creating pipeline')
change message to `failed pipeline creation`

2021-12-29 10:54 UTC, Lalee10 commented on basepair/api.py
> +      eprint('failed updating pipeline')
change message to `failed pipeline creation`

2021-12-29 10:54 UTC, Lalee10 commented on bin/basepair
> +  if args.file[0].endswith('.yaml') or args.file[0].endswith('.yml'):
use declared variable `yaml_path`, you can also simplify the condition by using a tuple as the suffix for `endsWith`

```Python
if yaml_path.endsWith('yaml', 'yml'):
```

2021-12-29 10:54 UTC, Lalee10 commented on bin/basepair
> +  if args.file[0].endswith('.yaml') or args.file[0].endswith('.yml'):
use declared variable `yaml_path`, you can also simplify the condition by using a tuple as the suffix for `endsWith`

```Python
if yaml_path.endsWith('yaml', 'yml'):
```

2021-12-29 10:54 UTC, Lalee10 commented on bin/basepair
> +  if args.file[0].endswith('.yaml') or args.file[0].endswith('.yml'):
use declared variable `yaml_path`, you can also simplify the condition by using a tuple as the suffix for `endsWith`

```Python
if yaml_path.endsWith('yaml', 'yml'):
```

2021-12-29 10:54 UTC, Lalee10 commented on bin/basepair
> +  if args.file[0].endswith('.yaml') or args.file[0].endswith('.yml'):
use declared variable `yaml_path`, you can also simplify the condition by using a tuple as the suffix for `endsWith`

```Python
if yaml_path.endsWith('yaml', 'yml'):
```

2021-12-29 12:09 UTC, Lalee10 approved these changes

2021-12-29 12:15 UTC, merged