Improvement:command-refactor
basepair/basepair-python pull request #82
Opened 2022-01-04 22:13 UTC by siddhant-basepair

This PR will change commands -

Updated Commands will be - 

Module
module get
module delete
module create
module update
module list
Can pass `-p or –pipeline` flag to list modules for specific pipeline

Pipeline
pipeline get
pipeline delete
pipeline create
pipeline update
pipeline list

Genome
genome get
genome list
                  
Sample
sample get
sample delete
sample create
sample update
sample download
sample list
Can pass `--project-id` flag to filter samples for a specific project

Project
project create
project update

File
file download

Analysis
analysis get
analysis delete
analysis create
analysis update
analysis download 
analysis download log
analysis reanalyze
analysis list

Related Ticket -
https://app.asana.com/0/1201368373933132/1201611319941112

2022-01-05 06:02 UTC, Lalee10 requested changes
- Many of the help messages are not accurate. Help messages for the flag `-u, --uid` are not accurate for many commands like module delete, module pipeline, file download etc. Please fix them and any other help messages.
- Run the help messages of each command at least once to verify your changes

2022-01-05 09:28 UTC, siddhant-basepair commented on bin/basepair
> +    '--project',
it was earlier like this so please tell me if this also needs to  be refactored.

2022-01-05 11:19 UTC, Lalee10 commented on bin/basepair
> +    '--project',
Yes, it does need to be refactored

2022-01-06 05:22 UTC, Lalee10 commented on bin/basepair
> +    '--project',
@siddhant-basepair this requirement has changed again, please define the args as per the updated doc

2022-01-06 16:50 UTC, blasvicco requested changes
I believe the file will become more readable if we move the argument parser to a separated file or module.

2022-01-06 22:30 UTC, siddhant-basepair commented on bin/basepair
> +  if args.datatype == 'module':
it really helped to refactor the CLI to an optimal state now it's much easier to work on.

2022-01-06 22:33 UTC, closed without merging