Improvement cli refactor
basepair/basepair-python pull request #84
Opened 2022-01-06 22:31 UTC by siddhant-basepair

2022-01-07 16:37 UTC, Lalee10 requested changes
Help text for commands where we can only provide a single ID is not accurate. Please ensure that help texts follow the CLI Spec wherever possible.
```
// Wrong message
The unique id(s) for pipeline

// Correct message
The unique id of the pipeline
```

![image](https://user-images.githubusercontent.com/38792700/148575834-aebcef5b-5f22-41d3-b496-47a2e1b42fa7.png)

2022-01-07 17:07 UTC, siddhant-basepair commented
> Help text for commands where we can only provide a single ID is not accurate. Please ensure that help texts follow the CLI Spec wherever possible.
> 
> ```
> // Wrong message
> The unique id(s) for pipeline
> 
> // Correct message
> The unique id of the pipeline
> ```
> 
> ![image](https://user-images.githubusercontent.com/38792700/148575834-aebcef5b-5f22-41d3-b496-47a2e1b42fa7.png)

You can actually delete multiple pipelines by providing more than one --uid same as before

2022-01-07 17:09 UTC, Lalee10 commented
> > Help text for commands where we can only provide a single ID is not accurate. Please ensure that help texts follow the CLI Spec wherever possible.
> > ```
> > // Wrong message
> > The unique id(s) for pipeline
> > 
> > // Correct message
> > The unique id of the pipeline
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/38792700/148575834-aebcef5b-5f22-41d3-b496-47a2e1b42fa7.png)
> 
> You can actually delete multiple pipelines by providing more than one --uid same as before

Oh alright, if that's the case then update the Basepair CLI Spec document

2022-01-07 18:00 UTC, blasvicco requested changes
Look great man. Please do not forget to pylint. I see wrong indentation using tabs.
A use of eval that need to be avoided.
If you want to get the instance you can use a dict for that following the next pattern:
```PYTHON
datatype_handler = {
  'analysis': Analysis,
  ...,
  'sample': Sample,
}

method = getattr(datatype_handler[args.datatype], method_name, None)
```

Also, review the code to avoid typos. There are message with double "..".
There are not needed returns like this ones:
```PYTHON
if condition:
  action()
  return
return
```
Mixed indentations between 2 and 4 spaces.
Many of these things will be alerted by pylint.

Take your time to review your own code. It is not about speed it is about quality.

2022-01-10 19:48 UTC, blasvicco requested changes
@siddhant-basepair it is looking better man.
There are a couple of minor improvements related with code standards and removing not necessary print + returns.
There is one related with performance that worry me. Looks like we are making multiple API calls to get items by there ids. If these require a lot of your effort we can create a new ticket in asana and add that improvement later.

2022-01-10 19:48 UTC, blasvicco commented on basepair/api.py
> +      'pipelines': 'get_pipelines',
Please sort fields alphabetically.

2022-01-10 19:48 UTC, blasvicco commented on bin/basepair
> +    'analysis':Analysis,
Add space between ':':
```PYTHON
'analysis': Analysis,
'file': File,
...
```

2022-01-10 19:48 UTC, blasvicco commented on bin/common_parser.py
> +  parser.set_defaults(scratch='.')
We can add the default as an argument in the add_argument method:
```PYTHON
parser.add_argument('--scratch', default='.', help='Scratch dir for files')
```

2022-01-10 19:48 UTC, blasvicco commented on bin/common_parser.py
> +    nargs='+',
Let's sort declarative arguments alphabetically.
```PYTHON
parser.add_argument(
  '-u',
  '--uid',
  default=None,
  help=f'The unique id(s) for {datatype}',
  nargs='+',
```

2022-01-10 19:48 UTC, blasvicco commented on bin/datatypes/__init__.py
> +from .module import Module
Sort imports alphabetically except that there are required dependencies.

2022-01-10 19:48 UTC, blasvicco commented on bin/datatypes/analysis.py
> +
Np need of this extra line.

2022-01-10 19:48 UTC, blasvicco commented on bin/datatypes/analysis.py
> +    uids=args.uid
Please add spaces between the operator:
```PYTHON
uids = args.uid
```

2022-01-10 19:48 UTC, blasvicco commented on bin/datatypes/analysis.py
> +      eprint('At least one uid required.')
Should we replace this for a:
```PYTHON
sys.exit('ERROR: At least one uid required.')
```
And remove the return.

2022-01-10 19:48 UTC, blasvicco commented on bin/datatypes/analysis.py
> +      eprint('ERROR: Workflow required.')
Similar as before. Looks like the right method to call here is the sys.exit()

2022-01-10 19:48 UTC, blasvicco commented on bin/datatypes/analysis.py
> +      if args.outdir:
???
Looks like this should be just:
```PYTHON
bp_api.get_log(uid, args.outdir)
```

2022-01-10 19:48 UTC, blasvicco commented on bin/datatypes/analysis.py
> +    if not analysis_id:
Invert the bool check to avoid extra operation:
```PYTHON
if analysis_id:
  update_info(bp_api, kind='analysis', uid=analysis_id, keys=keys, vals=vals)
sys.exit('Error: Analysis required.')
```

2022-01-10 19:48 UTC, blasvicco commented on bin/datatypes/analysis.py
> +      info = bp_api.get_analysis(uid)  # check analysis id is valid
This will need an optimization, looks like we are doing one API call per uid.
We should retrieve the list of analysis in one API call.

2022-01-10 19:48 UTC, blasvicco commented on bin/datatypes/analysis.py
> +      if info is None:
Maybe better to use `if not info:`

2022-01-10 19:48 UTC, blasvicco commented on bin/datatypes/sample.py
> +    update_info(bp_api, kind='sample', uid=args.sample,
Please break one argument per line and sort the declarative ones, alphabetically.

2022-01-10 19:48 UTC, blasvicco commented on bin/utils.py
> +  if kind == 'sample':
```PYTHON
res = { 'error': True, msg: f'Update {kind} not supported.' }
method_name = f'update_{kind}'
method = getattr(bp, method_name, None)
if callable(method):
  res = method(uid, data)
if res.get('error'):
  sys.exit(f"ERROR: {res.get('msg')}")
```

2022-01-10 20:36 UTC, siddhant-basepair commented on bin/datatypes/analysis.py
> +      if args.outdir:
what if outdir argument is not given? that's why we have both of them by if and else

2022-01-10 20:39 UTC, siddhant-basepair commented on bin/datatypes/analysis.py
> +      info = bp_api.get_analysis(uid)  # check analysis id is valid
this we can take up in another ticket of optimizations.

2022-01-10 20:56 UTC, blasvicco commented on bin/datatypes/analysis.py
> +      info = bp_api.get_analysis(uid)  # check analysis id is valid
Please go ahead and create the ticket.

2022-01-11 13:56 UTC, blasvicco requested changes

2022-01-11 13:56 UTC, blasvicco commented on bin/utils.py
> +import sys
Please remove utils. Looks like check_yaml should be placed in the common parser and should be called `is_valid_yaml_arg`.
The input for is_valid_yaml_arg should be the file list not the whole argument object.

About update_info, you can get rid of this method.
There is no need to create this wrapper for analysis and sample update.

2022-01-11 13:56 UTC, blasvicco commented on bin/datatypes/sample.py
> +        sys.exit('{} is not a valid sample id!'.format(uid))
If you make this a sys.exit, then the whole call of the script will stop.
This need to be a print.

2022-01-11 13:56 UTC, blasvicco commented on bin/datatypes/sample.py
> +        'get',
Please fix indentation to be only 2 spaces.

2022-01-11 13:56 UTC, blasvicco commented on bin/datatypes/sample.py
> +    update_info(bp_api,
The preferred format is:
```PYTHON
method(
  arg1,
  arg2,
)
```

2022-01-11 13:56 UTC, blasvicco commented on bin/datatypes/sample.py
> +          'username': args.payload_username,
Please fix indentations.

2022-01-11 13:56 UTC, blasvicco commented on bin/datatypes/sample.py
> +      sys.exit(1)
This make no sense. The second sys.exit will be never call.

2022-01-11 13:56 UTC, blasvicco commented on bin/datatypes/file.py
> +    if not args.uid:
Inver if check to avoid extra operator not.

2022-01-14 14:33 UTC, blasvicco requested changes
@siddhant-basepair Looks like you have to expend more time reviewing your own code.

2022-01-14 14:33 UTC, blasvicco commented on bin/datatypes/__init__.py
> +
Remove empty lines please.

2022-01-14 14:33 UTC, blasvicco commented on bin/datatypes/analysis.py
> +    if not uids:
Invert if to avoid extra not operator.
```PYTHON
if uids:
  for....
sys.exit('At least one uid required.')
```

2022-01-14 14:33 UTC, blasvicco commented on bin/datatypes/analysis.py
> +    if not uids:
Invert if to avoid not oeprator.

2022-01-14 14:33 UTC, blasvicco commented on bin/datatypes/analysis.py
> +    else:
No need of else.

2022-01-14 14:33 UTC, blasvicco commented on bin/datatypes/analysis.py
> +    if not args.uid:
Invert if.

2022-01-14 14:33 UTC, blasvicco commented on bin/datatypes/analysis.py
> +    if not args.uid:
Invert if.

2022-01-14 14:33 UTC, blasvicco commented on bin/datatypes/file.py
> +    else:
No need of else.

2022-01-14 14:33 UTC, blasvicco commented on bin/datatypes/file.py
> +        'download',
Wrong indentation.

2022-01-14 14:33 UTC, blasvicco commented on bin/datatypes/genome.py
> +        'get',
Wrong indentation.

2022-01-14 14:33 UTC, blasvicco commented on bin/datatypes/genome.py
> +        'list',
Wrong indentation.

2022-01-14 14:33 UTC, blasvicco commented on bin/datatypes/module.py
> +    if not uids:
Invert if.

2022-01-14 14:33 UTC, blasvicco commented on bin/datatypes/module.py
> +    return
No need of return.

2022-01-14 14:33 UTC, blasvicco commented on bin/datatypes/module.py
> +    return
No need of return.

2022-01-14 14:33 UTC, blasvicco commented on bin/datatypes/module.py
> +    if not uids:
Invert if.

2022-01-14 14:33 UTC, blasvicco commented on bin/datatypes/module.py
> +        'get',
Wrong indentation.

2022-01-14 14:33 UTC, blasvicco commented on bin/datatypes/module.py
> +        'create',
Wrong indentation.

2022-01-20 16:34 UTC, blasvicco requested changes

2022-01-20 16:34 UTC, blasvicco commented on basepair/infra/webapp/project.py
> +  def get_project_by_name(self, name, params={}, verify=True): # pylint: disable=dangerous-default-value
We already have a method for this:
https://github.com/basepair/basepair-python/blob/1f2812e8ed1abc8136c62bdf86d603ea914c8d7c/basepair/infra/webapp/abstract.py#L60

You can call it passing the proper params fields, something like:
```PYTHON
(Project(api_cfg)).list(params={'name__iexact': name})
```
You do not need to filter by username because we are already doing that in the API:
https://github.com/basepair/webapp/blob/5672c964bf0e31c5e33af6b11fbaef413eb7fd95/www/bpapp/api2/project.py#L73

2022-01-20 16:34 UTC, blasvicco commented on bin/basepair
>    if args.config:
Nicer if we follow the pattern:
```PYTHON
variable = 'fall_back_value'
if something:
  variable = 'other_value'
```

For instance here:
```PYTHON
conf = None
if args.config:
  with open(args.config, 'r', encoding='utf-8') as config_file:
      conf = json.load(config_file)
```

2022-01-20 16:34 UTC, blasvicco commented on bin/basepair
> +    help='Basepair datatype - module, pipeline, sample, analysis etc.',
Let's sort argument by names when apply.

2022-01-20 16:34 UTC, blasvicco commented on bin/datatypes/analysis.py
> +      res = {'error': True, 'msg': 'Update analysis not supported.'}
This make no sense? I guess you forgot to erase a testing code.
Also, you need to return previous line 61 if res has no error.

2022-01-20 16:34 UTC, blasvicco commented on bin/datatypes/analysis.py
> +          bp_api.delete_analysis(uid)
You are missing the returns here to prevent the sys.exit when does not apply.

2022-01-20 16:34 UTC, blasvicco commented on bin/datatypes/analysis.py
> +    sys.exit('Please add one or more uid')
You are missing the return in many methods to avoid calling the sys.exit when does not apply.

2022-01-20 16:35 UTC, blasvicco commented
You introduce several logic errors related with calling the sys.exit when does not apply. Please be aware of the logic of the function and test your changes.

2022-01-21 09:21 UTC, blasvicco requested changes

2022-01-21 09:21 UTC, blasvicco commented on basepair/api.py
> +      cache = f'{self.scratch}/json/config.json'
Sadly we cannot use this f'' for string interpolation due the api.py is being imported in bioinfo script that still use python 2.
Please revert these changes.

2022-01-21 12:42 UTC, siddhant-basepair commented on basepair/infra/webapp/project.py
> +  def get_project_by_name(self, name, params={}, verify=True): # pylint: disable=dangerous-default-value
I am removing this method as i added this as testing feature it makes no significance

2022-01-21 19:45 UTC, blasvicco requested changes

2022-01-21 19:45 UTC, blasvicco commented on basepair/infra/webapp/project.py
> +from basepair.helpers import eprint
No need of this import.

2022-01-21 19:45 UTC, blasvicco commented on basepair/infra/webapp/project.py
> +import requests
No need of this import.

2022-01-21 19:45 UTC, blasvicco commented on bin/basepair
> +    help='Basepair datatype - analysis, module, pipeline, sample, etc.',
Sort arguments.

2022-01-21 19:45 UTC, blasvicco commented on bin/basepair
>        sys.exit(1)
Looks like this can be improve to something like this:
```PYTHON
if args.config:
  return eprint('Using config file', args.config)
if 'BP_CONFIG_FILE' in os.environ:
  return eprint(f"Using config file {os.environ['BP_CONFIG_FILE']}")
return sys.exit('Please either use the -c or --config param or set the environment variable BP_CONFIG_FILE!')
```

2022-01-21 19:45 UTC, blasvicco commented on bin/datatypes/analysis.py
> +    if args.params:
```PYTHON
    if args.params:
      for param in args.params:
        node_id, arg, val = param.split(':')
        if node_id not in params['node']:
          params['node'][node_id] = {}
        params['node'][node_id][arg] = val
      
      return bp_api.create_analysis(
        control_ids=args.control or [],
        ignore_validation_warnings=args.ignore_warning,
        params=params,
        project_id=args.project,
        sample_ids=args.sample,
        workflow_id=args.workflow,
      )
    return sys.exit('You specified no parameters, submitting with default ones.')
```

2022-01-24 12:34 UTC, blasvicco requested changes

2022-01-24 12:34 UTC, blasvicco commented on bin/datatypes/module.py
> +    if not uids:
This still apply.

2022-01-24 12:34 UTC, blasvicco commented on bin/basepair
> +    help='Type of action to perform on datatype.',
Sort arguments alphabetically.

2022-01-24 12:34 UTC, blasvicco commented on bin/datatypes/project.py
> +            'params': json.dumps({
Wrong indentation.

2022-01-24 12:34 UTC, blasvicco commented on bin/datatypes/sample.py
> +    if args.payload_username is not None and args.payload_api_key is None:
Please improve this chain of if that make no sense.

2022-01-24 14:49 UTC, blasvicco requested changes

2022-01-24 14:49 UTC, blasvicco commented on bin/basepair
> +    help='Type of action to perform on datatype.',
@siddhant-basepair !!!

2022-01-25 14:57 UTC, blasvicco requested changes
Please where you see this:
```PYTHON
eprint(msg)
sys.exit(1)
```
Replace it just by
```PYTHON
sys.exit(msg)
```

2022-01-25 14:57 UTC, blasvicco commented on basepair/helpers/nice_print.py
> +      print(f"Sample id: {sample['id']}")
Saddly, this change could break current bioinfo python2 scripts that are using basepair cli.

2022-01-25 14:57 UTC, blasvicco commented on bin/basepair
> +    description=f'Basepair CLI, API version {basepair.__version__}',
This is not compatible with python2.

2022-01-25 14:57 UTC, blasvicco commented on bin/basepair
> +    return eprint('Using config file', args.config)
This is breaking the logic of the method.

2022-01-25 14:57 UTC, blasvicco commented on bin/basepair
> +    return eprint(f"Using config file {os.environ['BP_CONFIG_FILE']}")
This also is breaking the logic of the method.

2022-01-25 14:57 UTC, blasvicco commented on bin/basepair
> +  return sys.exit('Please either use the -c or --config param or set the environment variable BP_CONFIG_FILE!')
You can make it a method
```PYTHON
def validate_conf(args):
  '''Helper to validate the proper configuration argument is being set''''
  if args.config:
    return eprint('Using config file', args.config)
  if 'BP_CONFIG_FILE' in os.environ:
    return eprint(f"Using config file {os.environ['BP_CONFIG_FILE']}")
  return sys.exit('Please either use the -c or --config param or set the environment variable BP_CONFIG_FILE!')
 
 validate_conf(args)
```

or you can remove the returns and invert the if for the sys.exit.
```PYTHON
config_in_env = 'BP_CONFIG_FILE' in os.environ
if not (args.config or config_in_env):
  sys.exit('Please either use the -c or --config param or set the environment variable BP_CONFIG_FILE!')

print('Using config file {}'.format(
  os.environ['BP_CONFIG_FILE'] if config_in_env else args.config
))
```

2022-01-27 15:51 UTC, blasvicco approved these changes

2022-04-11 11:59 UTC, govind-basepair commented on basepair/helpers/nice_print.py
> -        analysis['meta']['num_files'],
the associated header 'num files' is still there. It should be removed too if you're removing the data index here.

2022-04-11 12:07 UTC, govind-basepair commented on basepair/infra/webapp/abstract.py
> +      401: 'You don\'t have access to resource with id {}.'.format(obj_id) if obj_id else 'You don\'t have access to this resource.',
What's the difference between the existing **_parse_response** and your new **_parse_analysis_response** method except for this line?

2022-04-11 12:10 UTC, govind-basepair commented on basepair/infra/webapp/module.py
> +    self.api_endpoint = protocol + '://' + cfg.get('host') + cfg.get('prefix') + 'pipeline/get_module'
please check if you can use f string here. if yes then refactor and replace all string concatenation with f string. if not then at least use format wherever you see this type of string concatenation.

2022-04-11 12:12 UTC, govind-basepair commented on basepair/infra/webapp/module.py
> +    self.api_endpoint = protocol + '://' + cfg.get('host') + cfg.get('prefix') + 'pipeline/get_module'
what are the possible values of the `cfg.get('prefix')`

2022-04-11 12:14 UTC, govind-basepair commented on basepair/utils/instance.py
> +    'memory': 32,
sort

2022-04-11 12:14 UTC, govind-basepair commented on basepair/utils/instance.py
> +    'nitro_based': True,
sort

2022-04-11 12:16 UTC, govind-basepair commented on tests/lib.py
> +                ' Please properly set BP {} API_CONFIG.'.format(conf_name)),
remove string concatenation using '+'

2022-04-11 12:18 UTC, govind-basepair commented on bin/datatypes/sample.py
> +# App imports
add new line above # App imports

2022-04-11 12:21 UTC, govind-basepair commented on bin/datatypes/sample.py
> +    eprint('Sample created successfully.')
Even if the sample creation failed. it will display `Sample created successfully.` message.

2022-04-11 12:22 UTC, govind-basepair commented on bin/datatypes/sample.py
> +      sys.exit('ERROR: Deleting Sample failed.')
Update the message - `'ERROR: Deleting Sample(s) failed.'`

2022-04-11 12:40 UTC, govind-basepair commented on bin/datatypes/sample.py
> +        all_fail = not bool(bp_api.delete_sample(uid)) and all_fail
How is this supposed to work? what happens when one of the delete operations fails?

2022-04-11 13:01 UTC, govind-basepair commented on bin/datatypes/sample.py
> +          data['info'] = data.get('info', {})
this line can be taken out of the loop.

2022-04-11 13:19 UTC, govind-basepair commented on bin/datatypes/project.py
> +    if not data and not params:
you missed one condition. please see the following implementation.
```
  if a and b:
    sys.exit(A and B both present)

  if a or b:
    if a:
      sys.exit(B not present)
    sys.exit(A not present)

  sys.exit(A and B both not present)
```

2022-04-11 13:21 UTC, govind-basepair commented on bin/datatypes/pipeline.py
> +      bp_api.create_pipeline({'yamlpath': args.file[0], 'force': args.force})
add check for args.file param. add a default fallback value for args.force

2022-04-11 17:48 UTC, siddhant-basepair commented on bin/datatypes/sample.py
> +        all_fail = not bool(bp_api.delete_sample(uid)) and all_fail
@govind-basepair it will return False if it fails. If all of them fail the all_fail value will be False. Otherwise it will be True.

2022-04-11 18:02 UTC, siddhant-basepair commented on bin/datatypes/pipeline.py
> +      bp_api.create_pipeline({'yamlpath': args.file[0], 'force': args.force})
@govind-basepair  args.file is already validated in is_valid_yaml_arg and 'force' parameter if not provided stores False.

2022-04-11 20:24 UTC, amiaynara requested changes

2022-04-11 20:24 UTC, amiaynara commented on basepair/api.py
> +        an answer is required of the user).
Please follow the format used in other method in docstring for other methods. Hint: `get_file_by_tags`

2022-04-11 20:24 UTC, amiaynara commented on bin/common_parser.py
> +  if not pattern.match(value):
I think we could use :
```
if pattern.match(value):
  return value
raise ...
```

2022-04-12 10:46 UTC, siddhant-basepair commented on basepair/api.py
> +      except:# pylint: disable=bare-except
@amiaynara There can be error related to YAML format. So I used a general Exception in lot of places. So that even if something fails we always fall back to a ERROR response.
I think you want exception to be broad but everywhere it will increase lot of code in Except clause. Since there can be multiple exceptions inside a code block.

2022-04-12 10:50 UTC, siddhant-basepair commented on basepair/helpers/nice_print.py
> -    print(tabulate(to_print, headers=[
@amiaynara  Currently there are only two statements. We don't want to fallback on 3 statements.

2022-04-12 16:04 UTC, siddhant-basepair commented on basepair/api.py
> +      except:# pylint: disable=bare-except
@blasvicco Let me know your suggestion about this.

2022-04-13 05:29 UTC, akrmohd commented on basepair/api.py
> +      print(data['force'])
please remove this redundant print statement

2022-04-13 05:36 UTC, akrmohd commented on basepair/api.py
> +          if data['force']:
Using `data['force']` will cause a traceback if data does not have force included. So if somebody is using api.py directly, he will have a hard time to debug.
`data.get('force')` should be used in place of `data['force']`

2022-04-13 06:15 UTC, siddhant-basepair commented on basepair/api.py
> +          if data['force']:
@akrmohd  We are sending 'force' key in data from datatype itself so there would be no KeyError. Your suggestion is also implemented.

2022-04-26 11:27 UTC, siddhant-basepair commented on basepair/api.py
> +        eprint('exists'+' ./'+filepath.split('/')[-1])
@amiaynara we have to support python2 as well

2022-04-29 10:39 UTC, govind-basepair requested changes

2022-04-29 10:39 UTC, govind-basepair commented on bin/datatypes/sample.py
> +        all_fail = not bool(bp_api.delete_sample(uid)) and all_fail
what is the one you intended to do here - 
```
1. all_fail = (not bool(bp_api.delete_sample(uid))) and all_fail
2. all_fail = not (bool(bp_api.delete_sample(uid)) and all_fail)
```

2022-04-29 11:13 UTC, govind-basepair commented on basepair/infra/webapp/abstract.py
> +      401: 'You don\'t have access to resource with id {}.'.format(obj_id) if obj_id else 'You don\'t have access to this resource.',
these 2 functions are unnecessary `_parse_obj_response, _parse_validated_response`. please use the existing function `_parse_response` and make changes if required but do not repeat the same function twice.

2022-05-12 07:31 UTC, aaeronn commented on basepair/api.py
>      if self.verbose == 2:
Yes, it is verbose value, let keep it static here for now

2022-05-12 07:32 UTC, aaeronn commented on basepair/helpers/nice_print.py
> +    to_print = [[sample[field] for field in headers] for sample in data]
yes, it is generating errors. Fixed

2022-05-13 12:21 UTC, blasvicco approved these changes

2022-05-13 12:22 UTC, merged